---
# tasks file for apache
- name: install httpd
  package:
        name: "{{ package_name }}"
        state: present
        
- name: start the httpd daemon
  systemd:
        name: "{{ package_name }}"
        state: started
        enabled: true

- name: copy index file to target
  copy:
        src: files/index.html
        dest: /var/www/html/index.html
  notify: restart Apache