---
- hosts: all
  become: true
  gather_facts: yes
  ignore_errors: true
  vars:
    user_name: kah
    group_name: devops
  vars_files:
    - variables.yml
  tasks:
    - name: check the time
      command: datekjh
#      when: ansible_distribution == "serge" or ansible_processor_nproc == 2
    - name: create user kah
      user:
        name: "{{user_name}}"
        comment: "kah Admin"
    - name: create group
      group:
        name: "{{group_name}}"
        state: present
    - name: Install package
      package:
        name: "{{pkg_name}}"
        state: present
